courses/urls.py
from django.urls import path
from . import views


app_name='courses'
urlpatterns = [
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('subject_list/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(),name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(),name='lesson_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpdateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessonDeleteView.as_view(),name='lesson_delete'),
]

slms/urls.py
from slms.settings import MEDIA_URL
from django.contrib import admin
from django.urls import path
import users
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('courses/',include('courses.urls'))
    
]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models
from django.template.defaultfilters import slugify
import os
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Standard(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(null=True, blank=True)
    description = models.TextField(max_length=500,blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


###images subject
def save_subject_image(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.subject_id:
        filename = 'Subject_Pictures/{}.{}'.format(instance.subject_id, ext)
    return os.path.join(upload_to, filename)

class Subject(models.Model):
    subject_id = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE, related_name='subjects')
    image = models.ImageField(upload_to=save_subject_image, blank=True, verbose_name='Subject Image')
    description = models.TextField(max_length=500,blank=True)
    
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.subject_id)
        super().save(*args, **kwargs)







#####saving lessons
def save_lesson_files(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.lesson_id:
        filename = 'lesson_files/{}/{}.{}'.format(instance.lesson_id,instance.lesson_id, ext)
        if os.path.exists(filename):
            new_name = str(instance.lesson_id) + str('1')
            filename =  'lesson_images/{}/{}.{}'.format(instance.lesson_id,new_name, ext)
    return os.path.join(upload_to, filename)





####lessons
class Lesson(models.Model):
    lesson_id = models.CharField(max_length=100, unique=True)
    Standard = models.ForeignKey(Standard, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE,related_name='lessons')
    name = models.CharField(max_length=250)
    position = models.PositiveSmallIntegerField(verbose_name="Chapter no.")
    slug = models.SlugField(null=True, blank=True)
    video = models.FileField(upload_to=save_lesson_files,verbose_name="Video", blank=True, null=True)
    ppt = models.FileField(upload_to=save_lesson_files,verbose_name="Presentations", blank=True)
    Notes = models.FileField(upload_to=save_lesson_files,verbose_name="Notes", blank=True)

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('courses:lesson_list', kwargs={'slug':self.subject.slug, 'standard':self.Standard.slug})

courses/forms.py
from django import forms
from .models import Lesson

class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ('lesson_id','name','position','video','ppt','Notes')

courses/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, DetailView,
                                    ListView, CreateView,
                                    UpdateView,DeleteView,FormView,)
from .models import Standard, Subject, Lesson
from .forms import LessonForm
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

# Create your views here.
class StandardListView(ListView):
    context_object_name = 'standards'
    model = Standard
    template_name = 'courses/standard_list_view.html'



class SubjectListView(DetailView):
    context_object_name = 'standards'
    model = Standard
    template_name = 'courses/subject_list_view.html'



class LessonListView(DetailView):
    context_object_name = 'subjects'
    model = Subject
    template_name = 'courses/lesson_list_view.html'


class LessonDetailView(DetailView):
    context_object_name = 'lessons'
    model = Lesson
    template_name = 'courses/lesson_detail_view.html'









##########create

class LessonCreateView(CreateView):
    form_class = LessonForm
    context_object_name = 'subject'
    model= Subject
    template_name = 'courses/lesson_create.html'

    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.standard
        return reverse_lazy('courses:lesson_list',kwargs={'standard':standard.slug,
                                                             'slug':self.object.slug})


    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.created_by = self.request.user
        fm.Standard = self.object.standard
        fm.subject = self.object
        fm.save()
        return HttpResponseRedirect(self.get_success_url())
    


class LessonUpdateView(UpdateView):
    fields = ('name','position','video','ppt','Notes')
    model= Lesson
    template_name = 'courses/lesson_update.html'
    context_object_name = 'lessons'



class LessonDeleteView(DeleteView):
    model= Lesson
    context_object_name = 'lessons'
    template_name = 'courses/lesson_delete.html'

    def get_success_url(self):
        print(self.object)
        standard = self.object.Standard
        subject = self.object.subject
        return reverse_lazy('courses:lesson_list',kwargs={'standard':standard.slug,'slug':subject.slug})





#def classesView(request,apple):
    

courses/templates/courses/courses.html
{% extends 'base.html' %}

{% block body %}



<!-- Style Start -->
<style>
     h2,
     h1 {
          margin-top: 3%;
          font-family: 'Josefin Sans', sans-serif;
          text-align: center;
          color: #0A043C;
     }
</style>
<!-- Style End -->


<!-- Html Start -->

<!-- Html End -->


<h1>This could be</h1>

<div class="container">
     {{user.all_users.class_list}}


     {% if user.all_users.user_type == 'teacher' or user.is_superuser %}
     <h3>Am i teacher or admin</h3>
     {% endif %}


</div>



{% endblock %}

courses/templates/courses/lesson_create.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" >
{% csrf_token %}
{{form.as_p}}
<input type="submit" name="submit" value="submit">
</form>


{% endblock %}

courses/templates/courses/lesson_delete.html
{% extends 'base.html' %}

{% block content %}
<h3>Are you sure you want to delete?</h3>
<form method="POST" >
{% csrf_token %}
{{form.as_p}}
<input type="submit" name="delete" value="delete">
 <a href="{% url 'courses:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">Cancel</a>
</form>


{% endblock %}

courses/templates/courses/lesson_detail_view.html
{% extends 'base.html' %}

{% block content %}

<br><br> <p>Created by: {{lessons.created_by}} on {{lessons.created_at}}</p><br><br>
<a href="{% url 'courses:lesson_update' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">Update</a>
<a href="{% url 'courses:lesson_delete' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">Delete</a>
{% endblock %}

courses/templates/courses/lesson_list_view.html
{% extends 'base.html' %}

{% block content %}




{% for lesson in  subjects.lessons.all%}
        

        <a href="{% url 'courses:lesson_detail' slug=lesson.slug subject=subjects.slug standard=lesson.Standard.slug %}"> Chapter-{{lesson.position}}: {{lesson.name}} </a><br><br>

{% endfor %}


<a href="{% url 'courses:lesson_create' standard=subjects.standard.slug slug=subjects.slug %}">create lesson</a>
{% endblock %}

courses/templates/courses/lesson_update.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" >
{% csrf_token %}
{{form.as_p}}
<input type="submit" name="submit" value="submit">
 <a href="{% url 'courses:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">Cancel</a>
</form>


{% endblock %}

courses/templates/courses/standard_list_view.html
{% extends 'base.html' %}

{% block body %}
<!-- Style Start -->
<style>
   h2,
   h1 {
        margin-top: 3%;
        font-family: 'Josefin Sans', sans-serif;
        text-align: center;
        color: #0A043C;
   }
</style>
<!-- Style End -->

<div class="container">

<p>{{request.user.all_users.class_list}}</p>

{% for standard in  standards %}
      {% if standard.name == user.all_users.class_list %}
   <a> {{standard.name}}</a><br><br><br>
{% endif %}
{% endfor %}

</div>

{% endblock %}

courses/templates/courses/subject_list_view.html
{% extends 'base.html' %}

{% block content %}




{% for subject in  standards.subjects.all%}
    <br><br> <p > {{subject.name}}</p><br>
       <p> {{subject.description|truncatechars:75}}<p><br><br>

{% endfor %}
{% endblock %}