courses/urls.py
from django.urls import path
from . import views


app_name='courses'
urlpatterns = [
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('subject_list/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(),name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(),name='lesson_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpdateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessonDeleteView.as_view(),name='lesson_delete'),
]

slms/urls.py
from slms.settings import MEDIA_URL
from django.contrib import admin
from django.urls import path
import users
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('courses/',include('courses.urls'))
    
]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>{% block title %} {% endblock %}</title>
 
  <!-- Font End -->
   <link rel="preconnect" href="https://fonts.googleapis.com">
   <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
   <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet"> <!-- font end -->
    <!-- Font End -->

</head>

<!-- Styling  -->
<style>
  * {
  box-sizing: border-box;
}

body {
  margin: 0px;
    background-color: #FFE3DE;
}

.nav {
  height: 50px;
  width: 100%;
  background-color: #03506F;
  font-family: 'Josefin Sans', sans-serif;
  position: relative;
}
.nav > .nav-header {
  display: inline;
}

.nav > .nav-header > .nav-title {
  display: inline-block;
  font-size: 22px;
  color: #fff;
  padding: 10px 10px 10px 10px;
}

.nav > .nav-btn {
  display: none;
}

.nav > .nav-links {
  display: inline;
  float: right ;
  font-size: 18px;
}

.nav > .nav-links > a {
  display: inline-block;
  padding: 13px 10px 13px 10px;
  text-decoration: none;
  color: #A3DDCB;
}

.nav > .nav-links > a:hover {
  background-color: #0A043C;
}

.nav > #nav-check {
  display: none;
}

@media (max-width:600px) {
  .nav > .nav-btn {
    display: inline-block;
    position: absolute;
    right: 0px;
    top: 0px;
  }
  .nav > .nav-btn > label {
    display: inline-block;
    width: 50px;
    height: 50px;
    padding: 13px;
  }
  .nav > .nav-btn > label:hover,.nav  #nav-check:checked ~ .nav-btn > label {
    background-color: #03506F;
  }
  .nav > .nav-btn > label > span {
    display: block;
    width: 25px;
    height: 10px;
    border-top: 2px solid #A3DDCB;
  }
  .nav > .nav-links {
    position: absolute;
    display: block;
    width: 50%;
    background-color: #03506F;
    height: 0px;
    transition: all 0.3s ease-in;
    overflow-y: hidden;
    top: 50px;
    left: 0px;
  }
  .nav > .nav-links > a {
    display: block;
    width: 100%;
  }
  .nav > #nav-check:not(:checked) ~ .nav-links {
    height: 0px;
  }
  .nav > #nav-check:checked ~ .nav-links {
    height: calc(100vh - 50px);
    overflow-y: auto;
  }
}
.nav-header-text
{
  color: #0A043C;
}
.nav-header-text:hover{
  color: #A3DDCB;
}
</style>
<!-- Styling End  -->


<body>

  {% block nav %}

  <div class="nav">
    <input type="checkbox" id="nav-check">
    <div class="nav-header">
      <div class="nav-title">
        <!-- come title here -->
        <a class="nav-header-text" href="{% url 'index' %}">Courses</a>
      </div>
    </div>
    <div class="nav-btn">
      <label for="nav-check">
        <span></span>
        <span></span>
        <span></span>
      </label>
    </div>
    
    <div class="nav-links">
      <a href="{% url 'profile' %}" target="_blank">Profile</a>
      <a href="{% url 'courses:subject_list' %}" target="_blank">Assignments</a>
      <a href="#" target="_blank">Notice</a>
      <a href="{% url 'courses:standard_list' %}" target="_blank">Forums</a>
      <a href="{% url 'user_logout' %}" target="_blank">Logout</a>
    </div>
  </div>
  
  <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand mb-0 h1" href="{% url 'index' %}">Courses</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav ml-auto">
        <li class="navbar-brand mb-0 h1">
          <a class="nav-link" href="{% url 'profile' %}">Profile</a>
        </li>
        <li class="navbar-brand mb-0 h1">
          <a class="nav-link" href="{% url 'courses:subject_list' %}">Assignments</a>
        </li>
        <li class="navbar-brand mb-0 h1">
          <a class="nav-link" href="#">Notice</a>
        </li>
        <li class="navbar-brand mb-0 h1">
          <a class="nav-link" href="{% url 'courses:standard_list' %}">Forums</a>
        </li>
        <li class="navbar-brand mb-0 h1">
          <a class="nav-link" href="{% url 'user_logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </nav> -->
  {% endblock %}

  {% block body%}{% endblock %}















  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>

templates/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <a href="{% url 'index' %}">Home</a>
            
            <a href="{% url 'register' %}">Register</a>
            
            {% if user.is_authenticated %}
            <a href="{% url 'user_logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'user_login' %}">Login</a>
            
            {% endif %}
            <a href="{% url 'courses:standard_list' %}">standard</a>
            <h1>This is homepage</h1>
            
            {% block content %}

            
            
            {% endblock content %}
            
            
            

            

        </div>
    </div>
    
</body>
</html>